platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
#    repository: alpine
#    repository: uzyexe/nmap
#    repository: networkstatic/nmap
    tag: latest
inputs:
- name: nmap-ci

run:
  path: ./nmap-ci/ci/test.sh
