resources:
- name: nmap-ci
  type: git
  source:
    uri: git@github.com:kramse/nmap-ci.git
    branch: master

jobs:
- name: test-app
  plan:
  - get: nmap-ci
    trigger: true
  - task: tests
    file: nmap-ci/ci/build.yml
